valves = ['/ThePipeL/valve/x',
          '/ThePipeR/valve/x',
          '/C1V1/valve/x',
          '/C1V2/valve/x',
          '/C1V3/valve/x',
          '/C1V4/valve/x',
          '/C1V5/valve/x',
          '/C1V6/valve/x',
          '/C1V7/valve/x',
          '/C1V8/valve/x',
          '/C1V9/valve/x',
          '/C1V10/valve/x',
          '/C2V1/valve/x',
          '/C2V2/valve/x',
          '/C2V3/valve/x',
          '/C2V4/valve/x',
          '/C2V5/valve/x',
          '/C2V6/valve/x',
          '/C2V7/valve/x',
          '/C2V8/valve/x',
          '/C2V9/valve/x',
          '/C2V10/valve/x',
          '/A/L/valve/x', 
          '/A/R/valve/x',
          '/B/L/valve/x', 
          '/B/R/valve/x', 
          '/C/L/valve/x', 
          '/C/R/valve/x', 
          '/D/L/valve/x', 
          '/D/R/valve/x', 
]

ThePipe = {
    'ThePipeL': ['valve/x', 'roller/x', 'mute/x', 'tirapVert/x', 'tirapHoriz/x'],
    'ThePipeR': ['valve/x', 'roller/x', 'mute/x', 'tirapVert/x', 'tirapHoriz/x']
}
